services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./web:/usr/src/peeper
      - bundle:/usr/local/bundle
    command: ./bin/rails-entrypoint.sh
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./client:/usr/src/client    
    command: yarn dev